### ISSUE TITLE
Combine  SAN with SBR

### ISSUE THREAD

**Issue by keyxuliang** [D-X-Y/landmark-detection#30]
According to the SBR paper: the facial landmark detector can be replaced with other method.
Do you have a try to combine  SAN with SBR?
Thanks.

**Comment by D-X-Y** [comment]
Not yet. SAN costs maybe 20 hours to train a small network (CPM) and SBR is much slower than SAN due to the implementation of differentiable registration layer. Their combination will further slow down the training procedure, and thus we did not try this.

**Comment by keyxuliang** [comment]
I have a facial landmark detector network by myself. I want to combine the network with SBR to improve it's performance. As the SBR paper mentioned: you have tried regression network+SBR. Would you mind sharing a simple demo for that?
Thanks!

**Comment by D-X-Y** [comment]
I will discuss with my mentor about this, and let you know ASAP.

**Comment by keyxuliang** [comment]
Thank you very much.
What's the meaning of 'ASAP'?

**Comment by D-X-Y** [comment]
ASAP = as soon as possible

**Comment by keyxuliang** [comment]
Thanks! Looking forward to your sharing.

**Comment by D-X-Y** [comment]
Hi, @keyxuliang , I have discussed with my mentor. We can not release the regression model at this moment because our extension version is still under revision. If you want to use a regression-based detector, the simplest way is to use MobileNet backbone (https://github.com/tonylins/pytorch-mobilenet-v2/blob/master/MobileNetV2.py), and replace its classifier by a (number-of-points*2)-dimensional FC layer.

**Comment by keyxuliang** [comment]
Ok，I will  try it.

**Comment by D-X-Y** [comment]
Please feel free to re-open it if need.
