### ISSUE TITLE
[TS3] Execution Time on CPU

### ISSUE THREAD

**Issue by An-Shank** [D-X-Y/landmark-detection#37]
Hi,

Can you give details of the execution time per image when running on CPU? Can it be used for real-time landmark detection on videos?

**Comment by D-X-Y** [comment]
Thanks for your interests.
Since different hardware could yield different running time, we only report the FLOP here: https://github.com/D-X-Y/landmark-detection/tree/master/TS3#model-configs . You could test it on your own devices. If running on CPU, it can not be used for real-time detection on videos; if running on GPU, it can.
